### ISSUE TITLE
Does not use *latest* jsdom

### ISSUE THREAD

**Issue by salomvary** [dmnsgn/jest-environment-jsdom-latest#2]

**Comment by dmnsgn** [comment]
Updated to actual latest now that Jest dropped support for Node 4.
You probably want a specific jsdom version though like this one https://github.com/SimenB/jest-environment-jsdom-sixteen

**Comment by UziTech** [comment]
@dmnsgn you should delete the `package-lock.json` file otherwise anyone who uses this will always get jsdom v16.2.0

https://github.com/dmnsgn/jest-environment-jsdom-latest/blob/9f484215c438232d04e867433fa837b01cb47c26/package-lock.json#L2079-L2080

**Comment by dmnsgn** [comment]
@UziTech hmm as far as I know if you `npm install jest-environment-jsdom-latest` it will install pacakge.json dependencies (with "jsdom": "latest") and the lock file is not taken into account, not even published.

**Comment by UziTech** [comment]
Not according to the [documentation](https://docs.npmjs.com/configuring-npm/package-locks.html)

> This file (package-lock.json) describes an exact, and more importantly reproducible node_modules tree. Once it’s present, any future installation will base its work off this file, instead of recalculating dependency versions off package.json.

In other words if `package-lock.json` exists npm will use it instead of `package.json` to calculate which versions of dependencies to install. And it is definitely published. You can download the tarball directly from npm by running `npm pack jest-environment-jsdom-latest` and unzipping the downloaded folder.

**Comment by UziTech** [comment]
The purpose of the lock file is to ensure that your dependents have the same versions of dependencies as your dev environment so bugs are easier to find and fix.

In most projects that is what you would want. In this project, however, that is the exact opposite of it's purpose.

**Comment by dmnsgn** [comment]
Running `npm pack jest-environment-jsdom-latest` and unzipping the folder is giving me the following tree:

```
.
├── README.md
├── build
│   └── index.js
└── package.json
```

with `"json": "latest"` in package.json.

As you can see, no package-lock.json here and that's normal:
> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

I understand the purpose of the lock file but I don't see how deleting it will change what a user will get when installing it: if you currently run `npm i jest-environment-jsdom-latest`, you will indeed get jsdom `16.2.0` in your package-lock.json but isn't that only because `16.2.0` is the latest version? And whenever a new jsdom version is published, installing this package again will result in the latest jsdom version installed?

**Comment by UziTech** [comment]
After a little more research it seem you are right. I thought `package-lock.json` was published and looked at when installing dependencies, but it seems it is only when cloning the repo and running `npm install` that npm looks at the `package-lock.json` file.

Thanks for taking the time to help me learn something new. 😁
